# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable
Layout/EndOfLine:
  EnforcedStyle: lf
Style/EvalWithLocation:
  Enabled: false
require:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
